language: java

addons:
  sonarcloud:
    organization: "gsharma-github"
    token:
      secure: "h7BRKBjNRJaUvjTRgOSpqeLXFKX1POaqYaDyfcakk4acPReEF2+e5z6095tFh1i0KC2pfe/YAYE8OiXzGhmvEeOtwSoehKCV20QaNsh2Il/7kX3OSzaoHEuD8m6UTUhTYPBvdk4TCq220cRrl3QQZbF+OcubjoieyjmtJS+esPhYmbwKJOFghSeGlvlP0HIqQk3yF0uWfMvLY1YJA4tzzZHK4HQ9FEXtrpm6y5trVtGEdGtCF0dzs1iBKIcBnJh7dgjIq0hw1dHK4YzSdL7oSrwnubOwFemOUbCCdSUsQLGCIhrp5PjWljom7bXuleJOve0veABRFPB0IyNtSn+FHi3H8e7KANJsmgL1d9g5eWDESTezSZW4/mLXteLRYnRoTK0/v9rk2+sP+Mn/8Ue4qeKl5ibW/SbMu1HW18U+cQxVvz8XH0lNyzwH3G6+NmMVG6HwJwkYiC7Xt+aksbWFSPi0mOS5+6NxMZ8plbhiLOzQrTjcuHXY6L56JLT1NOUK6uz6JAmS3wV1uFvQPMASKh0qa0+Jrbc1S3OZUoem5GKoKpf60x0uvzpR7LJn6rKzOVPbCAC2k7AJKSgiZbV0gk7giK2glPzHlORsm7M7wBm3+C6ycFX4B6jg/rQoLdAS02fVod72trUHxtTpexoSLKnqHWjdg4heNor1uIfLUf0="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 833d1b9f-28a4-48fe-a942-2cd12baadffe
